### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by 123456789asdfjkl** [liuruiyang98/Jittor-MLP#4]
Hi, thank you for your great work! I think the value of dim should be 2.
https://github.com/liuruiyang98/Jittor-MLP/blob/b86656b65cf5f18ba9eb760d1f7565ed95e7e96e/models_pytorch/hire_mlp.py#L113

**Comment by liuruiyang98** [comment]
Thanks for your care and correction, I made a mistake in the PyTorch :( but it was right in Jittor version.  Feel free to raise a PR if you would like, and let's continue to maintain Vision MLP together.
